create table tb_stock
(
    id               bigint generated by default as identity,
    ativo            boolean,
    data_atualizacao timestamp,
    data_criacao     timestamp not null,
    descricao        varchar(255),
    nome             varchar(255),
    valor            decimal(19, 2),
    primary key (id)
)